-- CreateTable
CREATE TABLE "INGREDIENTS" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "INGREDIENTS_pkey" PRIMARY KEY ("id")
);
