-- CreateTable
CREATE TABLE "PIZZAS" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PIZZAS_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PIZZA_INGREDIENTS" (
    "ingredientId" INTEGER NOT NULL,
    "pizzaId" INTEGER NOT NULL,

    CONSTRAINT "PIZZA_INGREDIENTS_pkey" PRIMARY KEY ("pizzaId","ingredientId")
);

-- AddForeignKey
ALTER TABLE "PIZZA_INGREDIENTS" ADD CONSTRAINT "PIZZA_INGREDIENTS_ingredientId_fkey" FOREIGN KEY ("ingredientId") REFERENCES "INGREDIENTS"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PIZZA_INGREDIENTS" ADD CONSTRAINT "PIZZA_INGREDIENTS_pizzaId_fkey" FOREIGN KEY ("pizzaId") REFERENCES "PIZZAS"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
